# Generated by Django 3.2.4 on 2021-06-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categorie_articles',
                'verbose_name_plural': 'Categorie_articless',
            },
        ),
        migrations.CreateModel(
            name='Marques_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marques_articles',
                'verbose_name_plural': 'Marques_articless',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image_site')),
                ('prix', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stock', models.BooleanField(default=True)),
                ('quantite', models.IntegerField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='website.categorie_articles')),
                ('marques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marque', to='website.marques_articles')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articless',
            },
        ),
    ]
